manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: mikigiri
      url-base: https://github.com/mikigiri
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: mikigiri
      import: app/west.yml
  self:
    path: config
