CONFIG_NFCT_PINS_AS_GPIOS=y

# Enable Analog Input
CONFIG_ADC=y
# Use async mode (Optional)
CONFIG_ADC_ASYNC=y

# Enable Analog Input Module
CONFIG_ANALOG_INPUT=y
# CONFIG_ANALOG_INPUT_LOG_LEVEL_DBG=y
# CONFIG_ANALOG_INPUT_REPORT_INTERVAL_MIN=22

# Enable logging for pre/post processed value
CONFIG_ANALOG_INPUT_LOG_DBG_RAW=y
CONFIG_ANALOG_INPUT_LOG_DBG_REPORT=y

# Just in case, you don't RTFM
CONFIG_INPUT=y


# Zephyr Config
CONFIG_USB_DEVICE_HID=y

# Add one more USB_HID_DEVICE. 
# Hence, zmk default use 2 HID, HID_0 for keyboard, HID_1 for mouse.
CONFIG_USB_HID_DEVICE_COUNT=3

# Module Config
CONFIG_ZMK_HID_IO=y

# Enable hid joystick
CONFIG_ZMK_HID_IO_JOYSTICK=y

# Enable hid mouse
CONFIG_ZMK_HID_IO_MOUSE=y

# Enable hid haptic feedback
CONFIG_ZMK_HID_IO_OUTPUT=y

# Enable logging
CONFIG_ZMK_HID_IO_LOG_LEVEL_DBG=y